POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "111",
  "email": "fa20-bcs-005@cuilahore.edu.pk",
  "role": "admin"
}



####

GET http://localhost:3000/protected-route
