GET http://localhost:3000/petition

####

GET http://localhost:3000/petition/647c5858cd528db249cfc101

####
POST http://localhost:3000/petition
Content-Type: application/json

{
  "title": "Modern pentathlon without riding!",
  "description": "After the fiasco of the performance of the rider Annika Schleu at the equestrian competition of the modern pentathlon, it became finally obvious that equestrianism should no longer be a part of this competition. Pentathletes are athletes who have to master several disciplines. This requires a great variety and a lot of different training from the athletes.",
  "image": "2023-06-04T12:00:00Z",
  "author": "Shafeeq paravakkal",
  "authorImage": "n/a",
  "supporters": "183441",
  "name": "shafeeq ",
  "email": "sp@gmail.com",
  "dateSigned": "2023-05-18",
  "petitionId": "3"
}


####
DELETE http://localhost:3000/petition/647c54930a9a87d4eda0dee7

####
PATCH http://localhost:3000/petition/64823db83867099f2fd33103
Content-Type: application/json

{
  "image": "2023-06-04T12:00:00Z"
}